### ISSUE TITLE
File suffix

### ISSUE THREAD

**Issue by alexpovel** [Umair-Bashir/Test_Project#1]
Hi Umair,

glad to see you got cracking! Your invite reached me well.

I saw your first file, `test`. If you give it an appropriate file suffix, in this case by naming it `test.py`, GitHub (and many other tools, IDEs, ...) will recognize the file contents (Python code) appropriately and apply syntax highlighting (among other things). For the syntax highlighting, see for example [here](https://github.com/ansible/ansible/blob/devel/setup.py).

Have fun.

**Comment by Umair-Bashir** [comment]
Hi Alex, 

Thank You for the comment. I made the necessary changes accordingly. Kindly let me know if I need to make any further changes with the code and your viewpoint on it. 

Regards.

**Comment by alexpovel** [comment]
Hey,

it's still two days until Wednesday, so I don't know whether you're still working on this or not. Your question towards any further needed changes makes it sound like you're finished?

[The current file](https://github.com/Umair-Bashir/Test_Project/blob/b873f4a3a3175713596bf67d0cc481b526534aa3/test.py) has a number of problems. The most obvious one is that it doesn't compile (try `python -m py_compile test.py`). Please fix this and any further errors.
